FROM ubuntu:16.04

MAINTAINER cyf

COPY hosts /hosts

RUN cd / \
 && apt-get update \
 && apt-get install -y git net-tools cmake openssl build-essential libssl-dev \
 && cat /hosts >> /etc/hosts \
 && git clone https://github.com/meyerd/n2n.git \
 && cd /n2n/n2n_v2 \
 && cmake . \
 && make \
 && make install \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* /n2n /hosts

ENTRYPOINT ["edge"]
